# Run integration tests from branch-based pull request
on:
  pull_request:

name: Integration tests

jobs:
  integration:
    runs-on: ubuntu-latest
    # Trusted, branch-based pull request with secret access
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:

    - name: Branch based PR checkout
      uses: actions/checkout@v2

    # <insert integration tests>

    # Comment on the PR to show that repository secrets can be used
    - name: Silly secrets availability POC
      uses: actions/github-script@v1
      env:
        number: ${{ github.event.client_payload.pull_request.number }}
        secret-message: ${{ secrets.MESSAGE }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            issue_number: process.env.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Well, hey there! 🤠 Psst, secret message: ${process.env.secret-message}.`
          })