name: Ok To Test

on:
  issue_comment:
    types: [created]

jobs:
  ok-to-test:
    runs-on: ubuntu-latest
    steps:
    # - name: Check for "/ok-to-test"
    #   uses: actions/github-script@v1
    #   with:
    #     github-token: ${{secrets.GITHUB_TOKEN}}
    #     script: |
    #       github.issues.addLabels({
    #         issue_number: context.issue.number,
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         labels: ['Triage']
    #       })
    - name: Check for "/ok-to-test"
      run: echo "$COMMENT"
      env: 
        COMMENT: ${{ github.event.issue_comment.comment }}

    # - name: Repository Dispatch
    #   if: success()
    #   uses: peter-evans/repository-dispatch@v1
    #   with:
    #     token: ${{ secrets.REPO_ACCESS_TOKEN }}
    #     repository: username/my-repo
    #     event-type: my-event
    #     client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
