name: Ok To Test

on:
  issue_comment:
    types: [created]

jobs:
  ok-to-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check for "/ok-to-test"
      run: echo "$COMMENT"
      env:
        COMMENT: ${{ github.event.comment.body }}
      if: contains(${{ github.event.comment.body }}, '/ok-to-test')

    - name: Repository Dispatch
      if: success()
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        event-type: ok-to-test
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
