# If someone with write access comments "/ok-to-test" on a pull request, emit a repository dispatch
name: Ok To Test

on:
  issue_comment:
    types: [created]

jobs:
  ok-to-test:
    runs-on: ubuntu-latest
    steps:
    - name: Slash Command Dispatch
      uses: peter-evans/slash-command-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        reaction-token: ${{ secrets.GITHUB_TOKEN }}
        issue-type: pull_request
        event-type-suffix: ''
        commands: ok-to-test
        permission: write
