on:
  push:
    branches:         # array of glob patterns matching against refs/heads. Optional; defaults to all
    - master          # triggers on pushes that contain changes in master
    - feature/*
  repository_dispatch:
    types: [ok-to-test]

name: Test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "Running tests!"
    - run: echo "$TOKEN"
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}