on:
  repository_dispatch:
    types: [ok-to-test]

name: Test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "Running tests!"
    - run: echo "$TOKEN"
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}