name: Greet first time contributors

on:
  push

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - uses: tibdex/github-app-token@master
      with:
        app_id: ${{ secrets.gh_app_id }}
        private_key: ${{ secrets.gh_private_key }}
