on:
  repository_dispatch:
    types: [ok-to-test]

name: Test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # But which ref or sha?. We have the pull request number in ${{ github.event.client_payload.number }}.
    - uses: actions/github-script@v1
      id: get-sha
      env:
        number: ${{ github.event.client_payload.number }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const pull = await github.pulls.get({
            ...context.repo,
            pull_number: process.env.number
          });
          console.log(pull);
          // TODO error handling
          return pull.merge_commit_sha;

    - uses: actions/checkout@v2
      with:
        ref: ${{ steps.get-sha.outputs.result }}

    - uses: actions/setup-node@v1
    - run: |
        npm i
        npm t