# Run unit tests on any branch/fork pull request
on:
  pull_request

name: Unit Test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
    - run: |
        npm i
        npm t